# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Flake M nice_nano_v2'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["flake_left","flake_right"]'
